name: DoDoUI
run-name: ${{ github.actor }} is build the project ğŸš€
on: workflow_dispatch
jobs:
  Build-Action:
    runs-on: windows-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Setup Vulkan SDK
        # You may pin to the exact commit or the version.
        # uses: humbletim/setup-vulkan-sdk@72eed4b9dbeac5de168f83da8e30b1d0f8ac7f14
        uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          # specify which Vulkan SDK components to install, e.g. Vulkan-Headers, Vulkan-Loader, Glslang
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          # specify whether to cache VULKAN_SDK/ results between runs (using github actions/cache)
          vulkan-use-cache: true
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          git submodule update --init --recursive
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
