name: DoDoUI
run-name: ${{ github.actor }} is build the project ğŸš€
on: workflow_dispatch
jobs:
  Build-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install Vulkan SDK
        # You may pin to the exact commit or the version.
        # uses: humbletim/install-vulkan-sdk@6aadcb709dbb8e4096dad20e35adaefec83d4b45
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          # official Vulkan SDK release version to use
          version: 1.2.198.1
          # whether to cache the downloaded vulkan_sdk.* installer file (using github actions/cache)
          cache: false
          # silence GitHub Annotation notice displayed if resolving `latest` into Vulkan SDK release number
          quiet: false
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          git submodule update --init --recursive
          cmake -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
